// GENERATED by the Prep FRM server: titles of the corpus entries. Do not edit by hand.
// Imported by entry versions: titles only, so that entries can cite each other without cycles.
#import "/_gabarit.typ": types-entree

#let corpus-titres = (
  "bayes": (type: "formule", titre: "Règle de Bayes"),
  "black-scholes-call": (type: "formule", titre: "Black-Scholes : call européen"),
  "capm": (type: "formule", titre: "CAPM"),
  "donnees-aleatoires": (type: "brique", titre: "Données aléatoires"),
  "duration-convexite": (type: "formule", titre: "Variation de prix : duration et convexité"),
  "histogramme": (type: "brique", titre: "Histogramme avec quantile"),
  "la-vie-a-un-sens": (type: "propriete", titre: "La Vie a un sens"),
  "la-vie-n-a-pas-de-sens": (type: "propriete", titre: "La Vie n'a pas de sens"),
  "le-sens-de-la-vie": (type: "definition", titre: "Le Sens de la Vie"),
  "loi-de-student": (type: "formule", titre: "Loi de Student"),
  "loi-normale": (type: "formule", titre: "Loi normale"),
  "monte-carlo": (type: "brique", titre: "Estimation Monte-Carlo"),
  "rendements-portefeuille": (type: "brique", titre: "Rendement et volatilité d'un portefeuille"),
  "trajectoires-prix": (type: "brique", titre: "Trajectoires de prix (mouvement brownien géométrique)"),
  "var-parametrique-normale": (type: "formule", titre: "VaR paramétrique (normale)"),
  "variance-portefeuille-2-actifs": (type: "formule", titre: "Variance d'un portefeuille à deux actifs"),
)

#let voir(id) = {
  if id not in corpus-titres { panic("Entrée inconnue du corpus : " + id) }
  let entry = corpus-titres.at(id)
  let style = types-entree.at(entry.type)
  text(fill: style.couleur, weight: "semibold")[→ #entry.titre]
}
