// GENERATED by the Prep FRM server: titles of the corpus entries. Do not edit by hand.
// Imported by entry versions: titles only, so that entries can cite each other without cycles.
#import "/_gabarit.typ": types-entree

#let corpus-titres = (
  "bayes": (type: "formule", titre: "Règle de Bayes"),
  "black-scholes-call": (type: "formule", titre: "Black-Scholes : call européen"),
  "black-scholes-call-europeen": (type: "brique", titre: "Black-Scholes : call européen"),
  "board-of-directors": (type: "definition", titre: "Board of Directors"),
  "capm": (type: "formule", titre: "CAPM"),
  "chief-risk-officer": (type: "definition", titre: "Chief Risk Officer - CRO"),
  "currency-risk": (type: "definition", titre: "Currency Risk"),
  "donnees-aleatoires": (type: "brique", titre: "Données aléatoires"),
  "duration-convexite": (type: "formule", titre: "Variation de prix : duration et convexité"),
  "economic-capital": (type: "definition", titre: "Economic Capital"),
  "equity-risk": (type: "definition", titre: "Equity Risk"),
  "foreign-exchange-risk": (type: "definition", titre: "Foreign Exchange Risk"),
  "histogramme": (type: "brique", titre: "Histogramme avec quantile"),
  "interest-rate-risk": (type: "definition", titre: "Interest Rate Risk"),
  "la-vie-a-un-sens": (type: "propriete", titre: "La Vie a un sens"),
  "la-vie-n-a-pas-de-sens": (type: "propriete", titre: "La Vie n'a pas de sens"),
  "le-sens-de-la-vie": (type: "definition", titre: "Le Sens de la Vie"),
  "loi-de-student": (type: "formule", titre: "Loi de Student"),
  "loi-normale": (type: "formule", titre: "Loi normale"),
  "monte-carlo": (type: "brique", titre: "Estimation Monte-Carlo"),
  "option": (type: "definition", titre: "Option call"),
  "rendements-portefeuille": (type: "brique", titre: "Rendement et volatilité d'un portefeuille"),
  "reputation-risk": (type: "definition", titre: "Reputation Risk"),
  "risk-free-rate-rfr": (type: "definition", titre: "Risk Free Rate (rfr)"),
  "risk-reward-tradeoff-principle": (type: "theoreme", titre: "Risk-Reward Tradeoff Principle"),
  "specific-risk": (type: "definition", titre: "Specific Risk"),
  "systemic-risk": (type: "definition", titre: "Systemic Risk"),
  "time-value-of-money": (type: "definition", titre: "Time Value of Money"),
  "trajectoires-prix": (type: "brique", titre: "Trajectoires de prix (mouvement brownien géométrique)"),
  "unexpected-loss": (type: "definition", titre: "Unexpected Loss"),
  "var-parametrique-normale": (type: "formule", titre: "VaR paramétrique (normale)"),
  "variance-portefeuille-2-actifs": (type: "formule", titre: "Variance d'un portefeuille à deux actifs"),
)

#let voir(id) = {
  if id not in corpus-titres { panic("Entrée inconnue du corpus : " + id) }
  let entry = corpus-titres.at(id)
  let style = types-entree.at(entry.type)
  text(fill: style.couleur, weight: "semibold")[→ #entry.titre]
}
