// GENERATED by the Prep FRM server: the full corpus, for notes only. Do not edit by hand.
// Each version sits behind a closure: its file is evaluated only when a note inserts it.
#import "/_gabarit.typ": bloc-entree
#import "/_corpus-titres.typ": corpus-titres, voir

#let corpus-versions = (
  "anti-money-laundering-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/anti-money-laundering-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "bankruptcy-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/bankruptcy-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "bayes": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/bayes/baptiste.typ", hypotheses: none, limites: none),
  ),
  "black-scholes-call": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/black-scholes-call/baptiste.typ", hypotheses: () => include "corpus/black-scholes-call/baptiste.hypotheses.typ", limites: () => include "corpus/black-scholes-call/baptiste.limites.typ"),
  ),
  "black-scholes-call-europeen": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/black-scholes-call-europeen/baptiste.typ", hypotheses: none, limites: none),
  ),
  "board-of-directors": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/board-of-directors/baptiste.typ", hypotheses: none, limites: none),
  ),
  "business-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/business-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "case-northern-rock": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/case-northern-rock/baptiste.typ", hypotheses: none, limites: none),
  ),
  "chief-risk-officer": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/chief-risk-officer/baptiste.typ", hypotheses: none, limites: none),
  ),
  "commodity-price-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/commodity-price-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "compliance-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/compliance-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "currency-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/currency-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "cyber-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/cyber-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "default-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/default-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "diversifiable-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/diversifiable-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "donnees-aleatoires": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/donnees-aleatoires/baptiste.typ", hypotheses: none, limites: none),
  ),
  "duration-convexite": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/duration-convexite/baptiste.typ", hypotheses: none, limites: none),
  ),
  "economic-capital": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/economic-capital/baptiste.typ", hypotheses: none, limites: none),
  ),
  "entreprise-risk-management": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/entreprise-risk-management/baptiste.typ", hypotheses: none, limites: none),
  ),
  "equity-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/equity-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "expected-loss": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/expected-loss/baptiste.typ", hypotheses: none, limites: none),
  ),
  "expected-loss-formula": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/expected-loss-formula/baptiste.typ", hypotheses: () => include "corpus/expected-loss-formula/baptiste.hypotheses.typ", limites: () => include "corpus/expected-loss-formula/baptiste.limites.typ"),
  ),
  "exposure-at-default": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/exposure-at-default/baptiste.typ", hypotheses: none, limites: none),
  ),
  "foreign-exchange-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/foreign-exchange-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "funding-liquidity-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/funding-liquidity-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "histogramme": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/histogramme/baptiste.typ", hypotheses: none, limites: none),
  ),
  "idiosyncratic-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/idiosyncratic-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "interest-rate-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/interest-rate-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "legal-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/legal-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "liquidity-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/liquidity-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "loi-de-student": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/loi-de-student/baptiste.typ", hypotheses: none, limites: none),
  ),
  "loi-normale": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/loi-normale/baptiste.typ", hypotheses: none, limites: none),
  ),
  "loss-given-default": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/loss-given-default/baptiste.typ", hypotheses: none, limites: none),
  ),
  "market-liquidity-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/market-liquidity-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "market-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/market-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "monte-carlo": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/monte-carlo/baptiste.typ", hypotheses: none, limites: none),
  ),
  "operational-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/operational-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "option": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/option/baptiste.typ", hypotheses: none, limites: none),
  ),
  "point-in-time": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/point-in-time/baptiste.typ", hypotheses: none, limites: none),
  ),
  "probability-of-default": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/probability-of-default/baptiste.typ", hypotheses: none, limites: none),
  ),
  "rendements-portefeuille": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/rendements-portefeuille/baptiste.typ", hypotheses: none, limites: none),
  ),
  "reputation-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/reputation-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "risk-free-rate-rfr": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/risk-free-rate-rfr/baptiste.typ", hypotheses: none, limites: none),
  ),
  "risk-reward-tradeoff-principle": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/risk-reward-tradeoff-principle/baptiste.typ", hypotheses: none, limites: none),
  ),
  "risk-tolerance": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/risk-tolerance/baptiste.typ", hypotheses: none, limites: none),
  ),
  "specific-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/specific-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "strategic-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/strategic-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "systematic-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/systematic-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "tail-loss": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/tail-loss/baptiste.typ", hypotheses: none, limites: none),
  ),
  "time-value-of-money": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/time-value-of-money/baptiste.typ", hypotheses: none, limites: none),
  ),
  "trading-liquidity-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/trading-liquidity-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "trajectoires-prix": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/trajectoires-prix/baptiste.typ", hypotheses: none, limites: none),
  ),
  "unexpected-loss": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/unexpected-loss/baptiste.typ", hypotheses: none, limites: none),
  ),
  "unsystematic-risk": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/unsystematic-risk/baptiste.typ", hypotheses: none, limites: none),
  ),
  "var-parametrique-normale": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/var-parametrique-normale/baptiste.typ", hypotheses: none, limites: none),
  ),
  "variance-portefeuille-2-actifs": (
    "baptiste": (initiales: "BD", corps: () => include "corpus/variance-portefeuille-2-actifs/baptiste.typ", hypotheses: none, limites: none),
  ),
)

// One version in its box; a section that the version does not have is none.
#let boite(meta, version) = bloc-entree(
  meta.type, meta.titre, version.initiales, (version.corps)(),
  hypotheses: if version.hypotheses != none { (version.hypotheses)() },
  limites: if version.limites != none { (version.limites)() },
)

#let entree(id, auteur: none) = {
  if id not in corpus-titres { panic("Entrée inconnue du corpus : " + id) }
  let meta = corpus-titres.at(id)
  let versions = corpus-versions.at(id, default: (:))
  if auteur != none {
    if auteur not in versions { panic("Pas de version valide de « " + auteur + " » pour l'entrée " + id) }
    boite(meta, versions.at(auteur))
  } else {
    if versions.len() == 0 { panic("L'entrée " + id + " n'a encore aucune version valide") }
    for (author, version) in versions {
      boite(meta, version)
    }
  }
}
