// GENERATED by the Prep FRM server: the full corpus, for notes only. Do not edit by hand.
// Each text sits behind a closure: its file is evaluated only when a note inserts it. An entry
// whose text does not compile shows the last texts that did (corpus/<id>/valide/).
#import "/_gabarit.typ": bloc-entree
#import "/_corpus-titres.typ": corpus-titres, voir

#let corpus-textes = (
  "anti-money-laundering-risk": (corps: () => include "corpus/anti-money-laundering-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "bankruptcy-risk": (corps: () => include "corpus/bankruptcy-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "bayes": (corps: () => include "corpus/bayes/texte.typ", hypotheses: none, limites: none, variables: none),
  "black-scholes-call": (corps: () => include "corpus/black-scholes-call/texte.typ", hypotheses: () => include "corpus/black-scholes-call/hypotheses.typ", limites: () => include "corpus/black-scholes-call/limites.typ", variables: none),
  "black-scholes-call-europeen": (corps: () => include "corpus/black-scholes-call-europeen/texte.typ", hypotheses: none, limites: none, variables: none),
  "board-of-directors": (corps: () => include "corpus/board-of-directors/texte.typ", hypotheses: none, limites: none, variables: none),
  "business-risk": (corps: () => include "corpus/business-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "case-northern-rock": (corps: () => include "corpus/case-northern-rock/texte.typ", hypotheses: none, limites: none, variables: none),
  "chief-risk-officer": (corps: () => include "corpus/chief-risk-officer/texte.typ", hypotheses: none, limites: none, variables: none),
  "commodity-price-risk": (corps: () => include "corpus/commodity-price-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "compliance-risk": (corps: () => include "corpus/compliance-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "currency-risk": (corps: () => include "corpus/currency-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "cyber-risk": (corps: () => include "corpus/cyber-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "default-risk": (corps: () => include "corpus/default-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "diversifiable-risk": (corps: () => include "corpus/diversifiable-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "donnees-aleatoires": (corps: () => include "corpus/donnees-aleatoires/texte.typ", hypotheses: none, limites: none, variables: none),
  "duration-convexite": (corps: () => include "corpus/duration-convexite/texte.typ", hypotheses: none, limites: none, variables: none),
  "economic-capital": (corps: () => include "corpus/economic-capital/texte.typ", hypotheses: none, limites: none, variables: none),
  "entreprise-risk-management": (corps: () => include "corpus/entreprise-risk-management/texte.typ", hypotheses: none, limites: none, variables: none),
  "equity-risk": (corps: () => include "corpus/equity-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "expected-loss": (corps: () => include "corpus/expected-loss/texte.typ", hypotheses: none, limites: none, variables: none),
  "expected-loss-formula": (corps: () => include "corpus/expected-loss-formula/texte.typ", hypotheses: () => include "corpus/expected-loss-formula/hypotheses.typ", limites: () => include "corpus/expected-loss-formula/limites.typ", variables: none),
  "exposure-at-default": (corps: () => include "corpus/exposure-at-default/texte.typ", hypotheses: none, limites: none, variables: none),
  "foreign-exchange-risk": (corps: () => include "corpus/foreign-exchange-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "funding-liquidity-risk": (corps: () => include "corpus/funding-liquidity-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "histogramme": (corps: () => include "corpus/histogramme/texte.typ", hypotheses: none, limites: none, variables: none),
  "idiosyncratic-risk": (corps: () => include "corpus/idiosyncratic-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "interest-rate-risk": (corps: () => include "corpus/interest-rate-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "legal-risk": (corps: () => include "corpus/legal-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "liquidity-risk": (corps: () => include "corpus/liquidity-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "loi-de-student": (corps: () => include "corpus/loi-de-student/texte.typ", hypotheses: none, limites: none, variables: none),
  "loi-normale": (corps: () => include "corpus/loi-normale/texte.typ", hypotheses: none, limites: none, variables: none),
  "loss-given-default": (corps: () => include "corpus/loss-given-default/texte.typ", hypotheses: none, limites: none, variables: none),
  "market-liquidity-risk": (corps: () => include "corpus/market-liquidity-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "market-risk": (corps: () => include "corpus/market-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "monte-carlo": (corps: () => include "corpus/monte-carlo/texte.typ", hypotheses: none, limites: none, variables: none),
  "operational-risk": (corps: () => include "corpus/operational-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "option": (corps: () => include "corpus/option/texte.typ", hypotheses: none, limites: none, variables: none),
  "point-in-time": (corps: () => include "corpus/point-in-time/texte.typ", hypotheses: none, limites: none, variables: none),
  "probability-of-default": (corps: () => include "corpus/probability-of-default/texte.typ", hypotheses: none, limites: none, variables: none),
  "rendements-portefeuille": (corps: () => include "corpus/rendements-portefeuille/texte.typ", hypotheses: none, limites: none, variables: none),
  "reputation-risk": (corps: () => include "corpus/reputation-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "risk-free-rate-rfr": (corps: () => include "corpus/risk-free-rate-rfr/texte.typ", hypotheses: none, limites: none, variables: none),
  "risk-reward-tradeoff-principle": (corps: () => include "corpus/risk-reward-tradeoff-principle/texte.typ", hypotheses: none, limites: none, variables: none),
  "risk-tolerance": (corps: () => include "corpus/risk-tolerance/texte.typ", hypotheses: none, limites: none, variables: none),
  "specific-risk": (corps: () => include "corpus/specific-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "strategic-risk": (corps: () => include "corpus/strategic-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "systematic-risk": (corps: () => include "corpus/systematic-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "tail-loss": (corps: () => include "corpus/tail-loss/texte.typ", hypotheses: none, limites: none, variables: none),
  "time-value-of-money": (corps: () => include "corpus/time-value-of-money/texte.typ", hypotheses: none, limites: none, variables: none),
  "trading-liquidity-risk": (corps: () => include "corpus/trading-liquidity-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "trajectoires-prix": (corps: () => include "corpus/trajectoires-prix/texte.typ", hypotheses: none, limites: none, variables: none),
  "unexpected-loss": (corps: () => include "corpus/unexpected-loss/texte.typ", hypotheses: none, limites: none, variables: none),
  "unsystematic-risk": (corps: () => include "corpus/unsystematic-risk/texte.typ", hypotheses: none, limites: none, variables: none),
  "var-parametrique-normale": (corps: () => include "corpus/var-parametrique-normale/texte.typ", hypotheses: none, limites: none, variables: none),
  "variance-portefeuille-2-actifs": (corps: () => include "corpus/variance-portefeuille-2-actifs/texte.typ", hypotheses: none, limites: none, variables: none),
)

// auteur: accepted for notes written when entries had one version per person; ignored.
#let entree(id, auteur: none) = {
  if id not in corpus-titres { panic("Entrée inconnue du corpus : " + id) }
  if id not in corpus-textes { panic("L'entrée " + id + " n'a encore aucun texte qui compile") }
  let meta = corpus-titres.at(id)
  let texte = corpus-textes.at(id)
  bloc-entree(
    meta.type, meta.titre, (texte.corps)(),
    hypotheses: if texte.hypotheses != none { (texte.hypotheses)() },
    limites: if texte.limites != none { (texte.limites)() },
    variables: texte.variables,
  )
}
